### ISSUE TITLE
Support for Modified Reinhard

### ISSUE THREAD

**Issue by andreped** [EIDOSLAB/torchstain#29]
An improved Reinhard normalization technique was proposed in this paper:
https://ieeexplore.ieee.org/document/9616117

As the original Vahadane implementation is extremely slow compared to the already existing implementations, i.e., Reinhard and Macenko. It might be a good idea to look into improving some of the existing methods.

It does not seem that the modified reinhard is that much different from the original implementation. Hence, API-wise, it might be a good idea to add a `method` argument to Reinhard, to choose which implementation of Reinhard to use.

**Comment by andreped** [comment]
I have made a PR which adds support for this for all backends: https://github.com/EIDOSLAB/torchstain/pull/30

**Comment by shaanroy** [comment]
Problem with original Reinhard method is that you should have chosen the target image properly, as the processed image's statistics is very much dependent on the target image's statistics. That's why, we proposed Modified Reinhard in which source image's background luminance is preserved as it is. Previously many researchers shown in their paper that, Reinhard did not work, because they choose target image very dark. However, our proposed method alleviated this limitation, because our proposed method transfers background color and contrast statistics from target to source, however, we preserved the background luminance. 

Before, you choose a target image, please consult with us.

**Comment by andreped** [comment]
@shaanroy Thank you for the clarification. The modifications you proposed to the Reinhard algorithm are surely relevant and technically sound, hence, why I wanted to add support for it in the first place. I'm a huge fan of the generic nature of Reinhard and actively use it in my own research, so it is great to see improvements being made :] Thanks for that!

Regarding my comment above:

> It does not seem that the modified reinhard is that much different from the original implementation. Hence, API-wise, it might be a good idea to add a `method` argument to Reinhard, to choose which implementation of Reinhard to use.

It was not my intention to degrade your work, with this comment. I was only asking whether the modifications I made to my reinhard implementation were correct, as I was surprised how simple implementing the proposed solution was. I'm sorry again if it came out differently than I intended.

As my implementation will soon be merged with the master branch (already merged with the development branch), it would be great if you could review the implementation to verify that it seems correct:
https://github.com/EIDOSLAB/torchstain/blob/development/torchstain/numpy/normalizers/reinhard.py#L51

**Comment by shaanroy** [comment]
Sure. I am happy to help.

Thanks & Regards,
Dr. Santanu Roy

**Comment by andreped** [comment]
Fixed in 17c2d2886027a34ecf190c199fc8bcc7ec3536d1.
